export const CHECK_USER_QUESTIONS_PENDING = 'CHECK_USER_QUESTIONS_PENDING';
export const CHECK_USER_QUESTIONS_FULFILLED = 'CHECK_USER_QUESTIONS_FULFILLED';
export const CHECK_USER_QUESTIONS_REJECTED = 'CHECK_USER_QUESTIONS_REJECTED';
