export const LAST_ONLINE_USERS_PENDING = 'LAST_ONLINE_USERS_PENDING';
export const LAST_ONLINE_USERS_FULFILLED = 'LAST_ONLINE_USERS_FULFILLED';
export const LAST_ONLINE_USERS_REJECTED = 'LAST_ONLINE_USERS_REJECTED';
