export const FILTERS_PENDING = 'FILTERS_PENDING';
export const FILTERS_FULFILLED = 'FILTERS_FULFILLED';
export const FILTERS_REJECTED = 'FILTERS_REJECTED';
export const FILTERS = 'FILTERS';
export const CHANGE_DATA = 'CHANGE_DATA';
