export const ANSWER_TO_SPECIAL_QUESTIONS_PENDING =
  'ANSWER_TO_SPECIAL_QUESTIONS_PENDING';
export const ANSWER_TO_SPECIAL_QUESTIONS_FULFILLED =
  'ANSWER_TO_SPECIAL_QUESTIONS_FULFILLED';
export const ANSWER_TO_SPECIAL_QUESTIONS_REJECTED =
  'ANSWER_TO_SPECIAL_QUESTIONS_REJECTED';
