import { StyleSheet, Dimensions } from 'react-native';

const screenWidth = Dimensions.get('window').width;

const styles = StyleSheet.create({
  backgroundView: {
    alignItems: 'center',
    height: '100%',
  },
  icon20: {
    width: 20,
    height: 20,
  },
  topView: {
    width: '100%',
    height: '15%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  topView2: {
    width: '100%',
    height: '30%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  titleText: {
    width: '100%',
    fontSize: 25,
    color: '#7755CD',
    fontWeight: 'bold',
    textAlign: 'center',
  },
  button: {
    width: '100%',
    height: 30,
    borderRadius: 15,
    backgroundColor: '#F3F3FB',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: 'red',
  },
  text: {
    color: 'black',
  },
  selectedText: {
    color: 'white',
  },
  descriptionText: {
    width: '100%',
    color: '#7755CD',
    textAlign: 'center',
  },
  item: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 10,
  },
  selectedStyle: {
    width: '100%',
    height: 30,
    borderRadius: 15,
    backgroundColor: 'red',
    alignItems: 'center',
    justifyContent: 'center',
  },
  genderView: {
    width: '100%',
    marginBottom: 20,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
  },
  man: {
    height: 100,
    width: 100,
    backgroundColor: '#7755CD',
    alignItems: 'center',
    justifyContent: 'center',
  },
  selectedMan: {
    height: 100,
    width: 100,
    backgroundColor: '#7755CD',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 5,
    borderColor: '#2ecc71',
  },
  women: {
    height: 100,
    width: 100,
    backgroundColor: '#F87878',
    alignItems: 'center',
    justifyContent: 'center',
  },
  selectedWomen: {
    height: 100,
    width: 100,
    backgroundColor: '#F87878',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 5,
    borderColor: '#2ecc71',
  },

  infoView: {
    width: '100%',
    flex: 1,
  },
  textInputViewLeft: {
    flexDirection: 'row',
    flex: 1,
    alignItems: 'center',
    marginRight: 5,
  },
  textInputViewRight: {
    flexDirection: 'row',
    flex: 1,
    alignItems: 'center',
    marginLeft: 5,
  },
  textInput: {
    borderBottomWidth: 2,
    borderBottomColor: '#e5e5e5',
    flex: 1,
    height: 50,
    flexDirection: 'row',
    alignItems: 'center',
  },
  textAreaView: {
    borderBottomWidth: 2,
    borderBottomColor: '#e5e5e5',
    flex: 1,
    height: 50,
    alignItems: 'center',
  },

  nexButton: {
    width: '50%',
    height: 50,
    borderRadius: 25,
    backgroundColor: '#7755CD',
    alignItems: 'center',
    justifyContent: 'center',
  },
  lastButton: {
    width: '50%',
    height: 50,
    borderRadius: 25,
    backgroundColor: 'white',
    borderWidth: 1,
    borderColor: '#7755CD',
    alignItems: 'center',
    justifyContent: 'center',
  },
  tabPage: {
    width: screenWidth,
    alignItems: 'center',
    paddingHorizontal: 20,
  },
  tabPageFull: {
    width: screenWidth,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 20,
  },

  codeView: {
    marginTop: 50,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
  },
  codeTextInput: {
    backgroundColor: '#e5e5e5',
    color: '#7755CD',
    fontSize: 20,
    fontWeight: 'bold',
    textAlign: 'center',
    width: 30,
    height: 60,
    marginRight: 10,
  },
  photosContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    width: screenWidth,
    height: screenWidth / 2,
  },
  photoViewLeft: {
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 20,
  },
  photoViewRight: {
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: 20,
  },
  photoLeft: {
    width: screenWidth / 3,
    height: screenWidth / 3,
    borderRadius: screenWidth / 3 / 2,
    borderColor: '#e5e5e5',
  },
  photoRight: {
    width: screenWidth / 3,
    height: screenWidth / 3,
    borderRadius: screenWidth / 3 / 2,
    borderColor: '#e5e5e5',
  },
  photoViewCenter: {
    marginTop: screenWidth / 3 / 2,
    position: 'absolute',
    alignItems: 'flex-end',
    justifyContent: 'flex-end',
    borderColor: '#e5e5e5',
  },
  photoCenter: {
    width: screenWidth / 2,
    height: screenWidth / 2,
    borderRadius: screenWidth / 2 / 2,
  },
  editButton: {
    width: 50,
    height: 50,
    position: 'absolute',
    borderRadius: 25,
    borderColor: 'white',
    borderWidth: 3,
    backgroundColor: '#F61D45',
    alignItems: 'center',
    justifyContent: 'center',
  },
  loading: {
    ...StyleSheet.absoluteFill,
    zIndex: 9,
    backgroundColor: 'rgba(34,34,34,0.6)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  errorWrapper: {
    marginBottom: -10,
    paddingHorizontal: 20,
  },
  errorText: {
    fontSize: 14,
    color: '#F61D45',
    textAlign: 'center',
    paddingVertical: 4,
  },
});

export default styles;
