export const GIVES_WANTED_ANSWERS_USERS_PENDING =
  'GIVES_WANTED_ANSWERS_USERS_PENDING';
export const GIVES_WANTED_ANSWERS_USERS_FULFILLED =
  'GIVES_WANTED_ANSWERS_USERS_FULFILLED';
export const GIVES_WANTED_ANSWERS_USERS_REJECTED =
  'GIVES_WANTED_ANSWERS_USERS_REJECTED';
